"""
5-Min Divergence Analysis: Breakout Candle Price Movement Study
===============================================================
Reads data from data_5min/ (generated by fetch_5min_data.py).
No authentication needed.

Signal Logic (5-min):
  - PE Buy: Spot Green (C > O) AND PE Green (C > O)
  - CE Buy: Spot Red (C < O) AND CE Green (C > O)

Signal Validity:
  - Valid only if NO candle breaks the signal low before the high is broken
  - High must be broken within the NEXT 2 candles after signal candle

Breakout Candle Analysis (the candle that broke the signal high):
  - UPSIDE  = breakout candle HIGH  - signal candle HIGH  (how high it went)
  - DOWNSIDE = signal candle HIGH   - breakout candle LOW  (how low it went)
  - Both expressed in absolute ₹ (not %, so you can directly set SL/TP)

Output:
  - Console: per-signal table
  - Two separate plots: CE movements and PE movements
  - CSV: all_signals_analysis.csv

Usage: python analyze_divergence_5min.py
"""

import os
import json
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")          # headless – saves PNGs; swap to "TkAgg" for interactive
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import warnings
warnings.filterwarnings("ignore")

DATA_DIR   = "data_5min"
OUT_DIR    = "analysis_output"
META_FILE  = f"{DATA_DIR}/metadata.json"
MAX_SIGNAL_CANDLES = 2      # High must break within 2 candles of signal candle

os.makedirs(OUT_DIR, exist_ok=True)


# ============================================================
# DATA LOADING
# ============================================================

def load_meta():
    if not os.path.exists(META_FILE):
        print(f"❌ Metadata not found: {META_FILE}")
        print("   Please run fetch_5min_data.py first!")
        return None
    with open(META_FILE) as f:
        return json.load(f)


def load_df(path):
    if not os.path.exists(path):
        return pd.DataFrame()
    df = pd.read_csv(path)
    df["datetime"] = pd.to_datetime(df["datetime"])
    df = df.sort_values("datetime").reset_index(drop=True)
    return df


# ============================================================
# DIVERGENCE SIGNAL DETECTION
# ============================================================

def detect_signals(spot_df, ce_df, pe_df):
    """
    Detect raw divergence signals on 5-min candles.
    Returns list of signal dicts (not yet validated for breakout).
    """
    signals = []

    spot = spot_df.set_index("datetime")
    ce   = ce_df.set_index("datetime")
    pe   = pe_df.set_index("datetime")

    common = spot.index.intersection(ce.index).intersection(pe.index)

    for ts in common:
        s = spot.loc[ts]
        c = ce.loc[ts]
        p = pe.loc[ts]

        # Handle duplicate rows
        if isinstance(s, pd.DataFrame): s = s.iloc[0]
        if isinstance(c, pd.DataFrame): c = c.iloc[0]
        if isinstance(p, pd.DataFrame): p = p.iloc[0]

        spot_green = s["close"] > s["open"]
        spot_red   = s["close"] < s["open"]
        ce_green   = c["close"] > c["open"]
        pe_green   = p["close"] > p["open"]

        if spot_green and pe_green:
            signals.append({
                "time":        ts,
                "type":        "PE_BUY",
                "option":      "PE",
                "signal_high": p["high"],
                "signal_low":  p["low"],
                "signal_open": p["open"],
                "signal_close":p["close"],
                "spot_open":   s["open"],
                "spot_close":  s["close"],
            })

        if spot_red and ce_green:
            signals.append({
                "time":        ts,
                "type":        "CE_BUY",
                "option":      "CE",
                "signal_high": c["high"],
                "signal_low":  c["low"],
                "signal_open": c["open"],
                "signal_close":c["close"],
                "spot_open":   s["open"],
                "spot_close":  s["close"],
            })

    return signals


# ============================================================
# BREAKOUT ANALYSIS
# ============================================================

def analyze_breakout(signal, option_df_indexed, all_times):
    """
    For a single signal:
      1. Check if a candle breaks the signal HIGH within MAX_SIGNAL_CANDLES candles.
         Validity: no candle breaks signal LOW before the high is broken.
      2. If valid, measure the breakout candle's UPSIDE and DOWNSIDE relative to signal_high.

    Returns analysis dict or None if signal invalid / no breakout.
    """
    sig_time     = signal["time"]
    sig_high     = signal["signal_high"]
    sig_low      = signal["signal_low"]

    # Get candles AFTER the signal candle (next 2 only)
    future_times = [t for t in all_times if t > sig_time]

    if not future_times:
        return None

    # Look at up to MAX_SIGNAL_CANDLES candles ahead
    for i, t in enumerate(future_times[:MAX_SIGNAL_CANDLES]):
        if t not in option_df_indexed.index:
            continue

        candle = option_df_indexed.loc[t]
        if isinstance(candle, pd.DataFrame):
            candle = candle.iloc[0]

        # If LOW broke below signal low BEFORE high breaks → signal invalidated
        if candle["low"] < sig_low:
            return None          # Invalid

        # If HIGH broke above signal high → valid breakout!
        if candle["high"] > sig_high:
            upside   = candle["high"] - sig_high   # how much it went up beyond entry
            downside = sig_high - candle["low"]     # how far below entry it dipped in same candle
            return {
                **signal,
                "breakout_time":    t,
                "breakout_candles": i + 1,          # 1 = next candle, 2 = candle after
                "signal_high":      sig_high,
                "breakout_high":    candle["high"],
                "breakout_low":     candle["low"],
                "upside_rs":        upside,
                "downside_rs":      downside,
            }

    # No breakout within 2 candles → signal expired
    return None


# ============================================================
# PLOTTING
# ============================================================

def plot_movements(results_df, option_type, out_dir):
    """
    Plot for CE or PE signals:
      - Histogram + KDE of UPSIDE and DOWNSIDE (₹)
      - Scatter: upside vs downside
      - Cumulative distribution
    """
    df = results_df[results_df["option"] == option_type].copy()
    if df.empty:
        print(f"  No valid {option_type} signals to plot.")
        return

    up  = df["upside_rs"].values
    dn  = df["downside_rs"].values
    n   = len(df)

    color_up = "#00c853"   # green
    color_dn = "#d50000"   # red

    fig = plt.figure(figsize=(16, 12))
    fig.suptitle(
        f"{option_type} Buy — Breakout Candle Movement Analysis  (n={n} valid signals)",
        fontsize=15, fontweight="bold", y=0.98
    )

    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

    # ── 1. UPSIDE histogram ──────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.hist(up, bins=20, color=color_up, alpha=0.75, edgecolor="white")
    ax1.axvline(np.mean(up), color="white", linestyle="--", linewidth=1.5,
                label=f"Mean ₹{np.mean(up):.2f}")
    ax1.axvline(np.median(up), color="yellow", linestyle=":", linewidth=1.5,
                label=f"Median ₹{np.median(up):.2f}")
    ax1.set_title("Upside (₹) Distribution", fontsize=11)
    ax1.set_xlabel("₹ above signal high", fontsize=9)
    ax1.set_ylabel("Count", fontsize=9)
    ax1.legend(fontsize=8)
    ax1.set_facecolor("#1e1e2e")
    ax1.tick_params(colors="white"); ax1.xaxis.label.set_color("white")
    ax1.yaxis.label.set_color("white"); ax1.title.set_color("white")

    # ── 2. DOWNSIDE histogram ────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.hist(dn, bins=20, color=color_dn, alpha=0.75, edgecolor="white")
    ax2.axvline(np.mean(dn), color="white", linestyle="--", linewidth=1.5,
                label=f"Mean ₹{np.mean(dn):.2f}")
    ax2.axvline(np.median(dn), color="yellow", linestyle=":", linewidth=1.5,
                label=f"Median ₹{np.median(dn):.2f}")
    ax2.set_title("Downside / Risk (₹) Distribution", fontsize=11)
    ax2.set_xlabel("₹ below signal high (in breakout candle)", fontsize=9)
    ax2.set_ylabel("Count", fontsize=9)
    ax2.legend(fontsize=8)
    ax2.set_facecolor("#1e1e2e")
    ax2.tick_params(colors="white"); ax2.xaxis.label.set_color("white")
    ax2.yaxis.label.set_color("white"); ax2.title.set_color("white")

    # ── 3. Scatter: upside vs downside ──────────────────────
    ax3 = fig.add_subplot(gs[0, 2])
    ax3.scatter(dn, up, color="#7c83fd", alpha=0.6, edgecolors="white", linewidths=0.5, s=30)
    # 1:1 line (equal upside and downside)
    maxval = max(up.max(), dn.max()) * 1.05
    ax3.plot([0, maxval], [0, maxval], color="yellow", linestyle="--",
             linewidth=1, label="Upside = Downside")
    ax3.set_title("Upside vs Downside per Signal", fontsize=11)
    ax3.set_xlabel("Downside ₹", fontsize=9); ax3.set_ylabel("Upside ₹", fontsize=9)
    ax3.legend(fontsize=8)
    ax3.set_facecolor("#1e1e2e")
    ax3.tick_params(colors="white"); ax3.xaxis.label.set_color("white")
    ax3.yaxis.label.set_color("white"); ax3.title.set_color("white")

    # ── 4. Cumulative distribution of UPSIDE ─────────────────
    ax4 = fig.add_subplot(gs[1, 0])
    sorted_up = np.sort(up)
    cdf = np.arange(1, n + 1) / n
    ax4.plot(sorted_up, cdf * 100, color=color_up, linewidth=2)
    for pct in [25, 50, 75, 90]:
        val = np.percentile(up, pct)
        ax4.axvline(val, color="gray", linestyle=":", linewidth=0.8)
        ax4.text(val + 0.05, pct - 4, f"P{pct}=₹{val:.1f}", fontsize=7, color="gray")
    ax4.set_title("Cumulative — Upside", fontsize=11)
    ax4.set_xlabel("Upside ₹", fontsize=9); ax4.set_ylabel("% of signals ≤ x", fontsize=9)
    ax4.set_facecolor("#1e1e2e"); ax4.set_facecolor("#1e1e2e")
    ax4.tick_params(colors="white"); ax4.xaxis.label.set_color("white")
    ax4.yaxis.label.set_color("white"); ax4.title.set_color("white")

    # ── 5. Cumulative distribution of DOWNSIDE ───────────────
    ax5 = fig.add_subplot(gs[1, 1])
    sorted_dn = np.sort(dn)
    ax5.plot(sorted_dn, cdf * 100, color=color_dn, linewidth=2)
    for pct in [25, 50, 75, 90]:
        val = np.percentile(dn, pct)
        ax5.axvline(val, color="gray", linestyle=":", linewidth=0.8)
        ax5.text(val + 0.05, pct - 4, f"P{pct}=₹{val:.1f}", fontsize=7, color="gray")
    ax5.set_title("Cumulative — Downside (Risk)", fontsize=11)
    ax5.set_xlabel("Downside ₹", fontsize=9); ax5.set_ylabel("% of signals ≤ x", fontsize=9)
    ax5.set_facecolor("#1e1e2e")
    ax5.tick_params(colors="white"); ax5.xaxis.label.set_color("white")
    ax5.yaxis.label.set_color("white"); ax5.title.set_color("white")

    # ── 6. Stats summary table ───────────────────────────────
    ax6 = fig.add_subplot(gs[1, 2])
    ax6.axis("off")
    stats = [
        ["Metric",          "Upside ₹",              "Downside ₹"],
        ["Count",           str(n),                  str(n)],
        ["Mean",            f"₹{np.mean(up):.2f}",   f"₹{np.mean(dn):.2f}"],
        ["Median",          f"₹{np.median(up):.2f}", f"₹{np.median(dn):.2f}"],
        ["Std Dev",         f"₹{np.std(up):.2f}",    f"₹{np.std(dn):.2f}"],
        ["P25",             f"₹{np.percentile(up,25):.2f}", f"₹{np.percentile(dn,25):.2f}"],
        ["P50",             f"₹{np.percentile(up,50):.2f}", f"₹{np.percentile(dn,50):.2f}"],
        ["P75",             f"₹{np.percentile(up,75):.2f}", f"₹{np.percentile(dn,75):.2f}"],
        ["P90",             f"₹{np.percentile(up,90):.2f}", f"₹{np.percentile(dn,90):.2f}"],
        ["Min",             f"₹{up.min():.2f}",      f"₹{dn.min():.2f}"],
        ["Max",             f"₹{up.max():.2f}",      f"₹{dn.max():.2f}"],
        ["Up>Dn signals",   f"{(up > dn).sum()} ({(up > dn).mean()*100:.0f}%)", "—"],
    ]
    tbl = ax6.table(cellText=stats[1:], colLabels=stats[0],
                    cellLoc="center", loc="center")
    tbl.auto_set_font_size(False); tbl.set_fontsize(8)
    tbl.scale(1.2, 1.4)
    for (r, c), cell in tbl.get_celld().items():
        cell.set_facecolor("#2d2d3f" if r % 2 == 0 else "#1e1e2e")
        cell.set_text_props(color="white")
        cell.set_edgecolor("#555566")
    ax6.set_title(f"{option_type} Stats Summary", fontsize=11, color="white")
    ax6.set_facecolor("#1e1e2e")

    fig.patch.set_facecolor("#13131f")

    out_path = f"{out_dir}/{option_type.lower()}_movement_analysis.png"
    plt.savefig(out_path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"  📊 Plot saved: {out_path}")
    return out_path


# ============================================================
# MAIN
# ============================================================

def main():
    print("=" * 60)
    print("5-MIN DIVERGENCE BREAKOUT ANALYSIS")
    print("=" * 60)

    meta = load_meta()
    if not meta:
        return

    trading_days = meta.get("dates", meta.get("trading_days", []))
    print(f"Days to analyse: {trading_days}")

    all_results = []

    for date_str in trading_days:
        day_info = meta["days"].get(date_str)
        if not day_info:
            print(f"  Skipping {date_str} — not in metadata")
            continue

        ce_sym = day_info["ce_symbol"]
        pe_sym = day_info["pe_symbol"]

        spot_df = load_df(f"{DATA_DIR}/nifty_spot_5min_{date_str}.csv")
        ce_df   = load_df(f"{DATA_DIR}/nifty_ce_5min_{date_str}.csv")
        pe_df   = load_df(f"{DATA_DIR}/nifty_pe_5min_{date_str}.csv")

        if any(df.empty for df in [spot_df, ce_df, pe_df]):
            print(f"  ⚠️  Skipping {date_str} — missing CSV files")
            continue

        print(f"\n{'='*50}")
        print(f"📅 {date_str} | CE: {ce_sym} (₹{day_info['ce_price_at_920']:.2f}) "
              f"| PE: {pe_sym} (₹{day_info['pe_price_at_920']:.2f})")
        print(f"{'='*50}")
        print(f"   Candles: Spot={len(spot_df)}, CE={len(ce_df)}, PE={len(pe_df)}")

        # Detect all raw signals
        raw_signals = detect_signals(spot_df, ce_df, pe_df)
        print(f"   Raw divergence signals: {len(raw_signals)}")

        # Build indexed option DFs for fast lookup
        ce_idx = ce_df.set_index("datetime").sort_index()
        pe_idx = pe_df.set_index("datetime").sort_index()

        # Merge all timestamps for CE and PE (to find subsequent candles)
        all_option_times = sorted(set(ce_idx.index.tolist() + pe_idx.index.tolist()))

        # Analyze each signal
        valid = 0
        for sig in raw_signals:
            opt_df_idx = pe_idx if sig["option"] == "PE" else ce_idx
            result = analyze_breakout(sig, opt_df_idx, all_option_times)
            if result:
                result["date"] = date_str
                all_results.append(result)
                valid += 1

        print(f"   Valid breakout signals:  {valid}")

    # ── Summary ──────────────────────────────────────────────
    if not all_results:
        print("\n❌ No valid signals found across all days. Check data files.")
        return

    results_df = pd.DataFrame(all_results)

    # Reorder columns for readability
    cols = [
        "date", "type", "option",
        "time", "breakout_time", "breakout_candles",
        "signal_high", "signal_low",
        "breakout_high", "breakout_low",
        "upside_rs", "downside_rs",
        "spot_open", "spot_close",
    ]
    results_df = results_df[[c for c in cols if c in results_df.columns]]

    csv_path = f"{OUT_DIR}/all_signals_analysis.csv"
    results_df.to_csv(csv_path, index=False)
    print(f"\n✅ All results saved: {csv_path}")

    # ── Print per-type stats ──────────────────────────────────
    for opt_type in ["CE", "PE"]:
        grp = results_df[results_df["option"] == opt_type]
        if grp.empty:
            continue
        up = grp["upside_rs"]; dn = grp["downside_rs"]
        print(f"\n{'─'*50}")
        print(f"  {opt_type} BUY Signals — {len(grp)} valid breakouts")
        print(f"{'─'*50}")
        print(f"  UPSIDE   | Mean: ₹{up.mean():.2f} | Median: ₹{up.median():.2f} "
              f"| P75: ₹{up.quantile(.75):.2f} | Max: ₹{up.max():.2f}")
        print(f"  DOWNSIDE | Mean: ₹{dn.mean():.2f} | Median: ₹{dn.median():.2f} "
              f"| P75: ₹{dn.quantile(.75):.2f} | Max: ₹{dn.max():.2f}")
        pct_up_wins = (up > dn).mean() * 100
        print(f"  Upside > Downside in {pct_up_wins:.1f}% of signals")
        print(f"  Suggested TP (P50 upside): ₹{up.median():.2f}")
        print(f"  Suggested SL (P75 downside): ₹{dn.quantile(.75):.2f}")

    # ── Generate Plots (CE and PE separate) ──────────────────
    print(f"\n📊 Generating plots → {OUT_DIR}/")
    ce_plot = plot_movements(results_df, "CE", OUT_DIR)
    pe_plot = plot_movements(results_df, "PE", OUT_DIR)

    print(f"\n{'='*60}")
    print(f"ANALYSIS COMPLETE")
    print(f"  CSV:  {csv_path}")
    if ce_plot: print(f"  CE plot:  {ce_plot}")
    if pe_plot: print(f"  PE plot:  {pe_plot}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
