"""
Backtest: 1-Min Divergence Strategy (₹1 SL / ₹1 TP)
=====================================================
Reads CSV data from data/ directory (generated by fetch_historical_data.py).
No authentication needed — purely offline backtesting.

Strategy:
- Divergence Signal on 1-min candles:
  - PE Buy: Spot Green (Close > Open) AND PE Green (Close > Open)
  - CE Buy: Spot Red (Close < Open) AND CE Green (Close < Open... wait, CE Green)
- Entry: Break of divergence candle's high (next candle high exceeds signal high)
- Stop Loss: Entry price - ₹1
- Take Profit: Entry price + ₹1
- Lot Size: 75 (1 NIFTY lot) → PnL = ±₹75 per trade
  (Updated: using 75 as standard NIFTY lot size; user said 65 so we use 75 if standard, 
   but user specifically said 65 so we use 65)
- Trailing SL: Simplified for candle-based backtest (strict 1:1)

Usage: python backtest_1min_divergence.py
"""

import os
import json
import pandas as pd
import pytz
from datetime import datetime
import logging
import glob

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

IST = pytz.timezone('Asia/Kolkata')

# ============================================================
# STRATEGY PARAMETERS
# ============================================================
SL_POINTS = 1.0       # ₹1 stop loss from entry
TP_POINTS = 1.0       # ₹1 take profit from entry
LOT_SIZE = 65         # 1 NIFTY lot (as specified by user: +₹65 per win, -₹65 per loss)

# ============================================================
# DATA LOADING
# ============================================================

def load_metadata():
    """Load metadata from data/metadata.json."""
    metadata_path = "data/metadata.json"
    if not os.path.exists(metadata_path):
        logger.error(f"Metadata file not found: {metadata_path}")
        logger.error("Please run fetch_historical_data.py first!")
        return None
    
    with open(metadata_path, "r") as f:
        return json.load(f)


def load_csv_data(filepath):
    """Load CSV data into DataFrame."""
    if not os.path.exists(filepath):
        logger.warning(f"File not found: {filepath}")
        return pd.DataFrame()
    
    df = pd.read_csv(filepath)
    df['datetime'] = pd.to_datetime(df['datetime'])
    return df


# ============================================================
# DIVERGENCE DETECTION (1-MIN)
# ============================================================

def detect_divergence_signals(spot_df, ce_df, pe_df):
    """
    Detect divergence signals on 1-min candles.
    
    Signal Logic:
    - PE Buy: Spot Green (Close > Open) AND PE Green (Close > Open)
    - CE Buy: Spot Red (Close < Open) AND CE Green (Close > Open)
    
    Returns list of signal dicts.
    """
    signals = []
    
    # Align timestamps
    spot_df = spot_df.set_index('datetime')
    ce_df = ce_df.set_index('datetime')
    pe_df = pe_df.set_index('datetime')
    
    # Find common timestamps
    common_times = spot_df.index.intersection(ce_df.index).intersection(pe_df.index)
    
    for ts in common_times:
        spot = spot_df.loc[ts]
        ce = ce_df.loc[ts]
        pe = pe_df.loc[ts]
        
        # Handle duplicate indices (take first)
        if isinstance(spot, pd.DataFrame):
            spot = spot.iloc[0]
        if isinstance(ce, pd.DataFrame):
            ce = ce.iloc[0]
        if isinstance(pe, pd.DataFrame):
            pe = pe.iloc[0]
        
        spot_green = spot['close'] > spot['open']
        spot_red = spot['close'] < spot['open']
        ce_green = ce['close'] > ce['open']
        pe_green = pe['close'] > pe['open']
        
        # PE Buy Signal: Spot Green AND PE Green
        if spot_green and pe_green:
            signals.append({
                'time': ts,
                'type': 'PE_BUY',
                'option_symbol': 'PE',
                'signal_high': pe['high'],
                'signal_low': pe['low'],
                'signal_open': pe['open'],
                'signal_close': pe['close'],
                'spot_open': spot['open'],
                'spot_close': spot['close'],
                'reason': f"Spot GREEN (O:{spot['open']:.2f} C:{spot['close']:.2f}) + PE GREEN (O:{pe['open']:.2f} C:{pe['close']:.2f})"
            })
        
        # CE Buy Signal: Spot Red AND CE Green
        if spot_red and ce_green:
            signals.append({
                'time': ts,
                'type': 'CE_BUY',
                'option_symbol': 'CE',
                'signal_high': ce['high'],
                'signal_low': ce['low'],
                'signal_open': ce['open'],
                'signal_close': ce['close'],
                'spot_open': spot['open'],
                'spot_close': spot['close'],
                'reason': f"Spot RED (O:{spot['open']:.2f} C:{spot['close']:.2f}) + CE GREEN (O:{ce['open']:.2f} C:{ce['close']:.2f})"
            })
    
    return signals


# ============================================================
# BACKTEST ENGINE
# ============================================================

def run_backtest_for_day(date_str, spot_df, ce_df, pe_df):
    """
    Run backtest for a single day.
    
    Rules:
    - After a signal candle, look for breakout (price > signal high) in subsequent candles
    - Entry = signal candle high (the breakout level)
    - SL = entry - ₹1
    - TP = entry + ₹1
    - For each candle AFTER entry:
      * If candle HIGH >= TP (entry + 1) → TP HIT (profit)
      * If candle LOW <= SL (entry - 1) → SL HIT (loss)
      * If BOTH could hit in same candle:
        - ENTRY CANDLE: TP wins (entry was an upward breakout, high was reached first)
        - SUBSEQUENT CANDLE: check if open is above entry → TP likely first; else SL likely first
    - Only 1 trade at a time (no overlapping trades)
    
    Returns list of trade dicts.
    """
    trades = []
    
    # Detect signals
    signals = detect_divergence_signals(spot_df.copy(), ce_df.copy(), pe_df.copy())
    logger.info(f"  [{date_str}] Detected {len(signals)} divergence signals")
    
    if not signals:
        return trades
    
    # Get option DataFrames indexed by time for candle iteration
    ce_indexed = ce_df.set_index('datetime').sort_index()
    pe_indexed = pe_df.set_index('datetime').sort_index()
    
    # Track state
    pending_signal = None  # Signal waiting for breakout
    active_trade = None    # Currently active trade
    
    # Sort all candle timestamps
    all_times = sorted(set(ce_indexed.index.tolist() + pe_indexed.index.tolist()))
    
    # Create signal lookup by time (keep the last signal at each timestamp)
    signal_by_time = {}
    for s in signals:
        signal_by_time[s['time']] = s
    
    for i, ts in enumerate(all_times):
        # Check if there's a new signal at this timestamp
        if ts in signal_by_time and active_trade is None:
            # Only accept new signal if no trade is active
            new_signal = signal_by_time[ts]
            pending_signal = new_signal
        
        # If we have a pending signal, check for breakout in SUBSEQUENT candles
        if pending_signal is not None and ts > pending_signal['time'] and active_trade is None:
            # Get the option candle to check breakout
            option_type = pending_signal['option_symbol']
            option_df = pe_indexed if option_type == 'PE' else ce_indexed
            
            if ts in option_df.index:
                candle = option_df.loc[ts]
                if isinstance(candle, pd.DataFrame):
                    candle = candle.iloc[0]
                
                # Check if this candle breaks the signal high
                if candle['high'] > pending_signal['signal_high']:
                    # ENTRY! Price broke above signal candle high
                    entry_price = pending_signal['signal_high']
                    sl_price = entry_price - SL_POINTS
                    tp_price = entry_price + TP_POINTS
                    
                    active_trade = {
                        'signal_time': pending_signal['time'],
                        'entry_time': ts,
                        'type': pending_signal['type'],
                        'option': option_type,
                        'entry_price': entry_price,
                        'sl': sl_price,
                        'tp': tp_price,
                        'reason': pending_signal['reason'],
                    }
                    
                    # === ENTRY CANDLE SL/TP CHECK ===
                    # Entry triggered because HIGH > signal_high (upward breakout).
                    # The price went UP to break signal_high, so the HIGH was reached
                    # on the way up. If the high >= TP, that means TP was hit FIRST
                    # (the upward move reached TP before any pullback to SL).
                    
                    hit_tp = candle['high'] >= tp_price
                    hit_sl = candle['low'] <= sl_price
                    
                    if hit_tp and hit_sl:
                        # Both levels touched in entry candle.
                        # Since entry is an UPWARD breakout, the high (TP direction)
                        # was reached FIRST, then price pulled back to low (SL).
                        # → TP wins on entry candle.
                        active_trade['exit_price'] = tp_price
                        active_trade['exit_time'] = ts
                        active_trade['result'] = 'TP'
                        active_trade['pnl'] = TP_POINTS * LOT_SIZE
                        trades.append(active_trade)
                        active_trade = None
                        pending_signal = None
                    elif hit_tp:
                        # Only TP hit → profit
                        active_trade['exit_price'] = tp_price
                        active_trade['exit_time'] = ts
                        active_trade['result'] = 'TP'
                        active_trade['pnl'] = TP_POINTS * LOT_SIZE
                        trades.append(active_trade)
                        active_trade = None
                        pending_signal = None
                    elif hit_sl:
                        # Only SL hit (price broke up then crashed below SL without reaching TP)
                        active_trade['exit_price'] = sl_price
                        active_trade['exit_time'] = ts
                        active_trade['result'] = 'SL'
                        active_trade['pnl'] = -SL_POINTS * LOT_SIZE
                        trades.append(active_trade)
                        active_trade = None
                        pending_signal = None
                    else:
                        # Trade still open, continue to next candle
                        pending_signal = None  # Signal consumed
                
                elif candle['low'] < pending_signal['signal_low']:
                    # Signal invalidated — price broke below signal candle low
                    pending_signal = None
        
        # If we have an active trade, check SL/TP on SUBSEQUENT candles
        if active_trade is not None and ts > active_trade['entry_time']:
            option_type = active_trade['option']
            option_df = pe_indexed if option_type == 'PE' else ce_indexed
            
            if ts in option_df.index:
                candle = option_df.loc[ts]
                if isinstance(candle, pd.DataFrame):
                    candle = candle.iloc[0]
                
                sl_price = active_trade['sl']
                tp_price = active_trade['tp']
                
                # === SUBSEQUENT CANDLE SL/TP CHECK ===
                # For formed candles, check:
                # - If HIGH >= TP → candle reached TP level
                # - If LOW <= SL → candle reached SL level
                # If BOTH in same candle → check which direction candle opened toward
                
                hit_tp = candle['high'] >= tp_price
                hit_sl = candle['low'] <= sl_price
                
                if hit_tp and hit_sl:
                    # Both levels touched — determine which hit first
                    # If candle opened above entry → price was moving up → TP likely first
                    # If candle opened below entry → price was moving down → SL likely first
                    if candle['open'] >= active_trade['entry_price']:
                        # Opened above entry, was going up → TP first
                        active_trade['exit_price'] = tp_price
                        active_trade['exit_time'] = ts
                        active_trade['result'] = 'TP'
                        active_trade['pnl'] = TP_POINTS * LOT_SIZE
                    else:
                        # Opened below entry, was going down → SL first
                        active_trade['exit_price'] = sl_price
                        active_trade['exit_time'] = ts
                        active_trade['result'] = 'SL'
                        active_trade['pnl'] = -SL_POINTS * LOT_SIZE
                    trades.append(active_trade)
                    active_trade = None
                elif hit_tp:
                    # TP hit → profit
                    active_trade['exit_price'] = tp_price
                    active_trade['exit_time'] = ts
                    active_trade['result'] = 'TP'
                    active_trade['pnl'] = TP_POINTS * LOT_SIZE
                    trades.append(active_trade)
                    active_trade = None
                elif hit_sl:
                    # SL hit → loss
                    active_trade['exit_price'] = sl_price
                    active_trade['exit_time'] = ts
                    active_trade['result'] = 'SL'
                    active_trade['pnl'] = -SL_POINTS * LOT_SIZE
                    trades.append(active_trade)
                    active_trade = None
    
    # Close any open trade at EOD (last candle close)
    if active_trade is not None:
        last_ts = all_times[-1]
        option_type = active_trade['option']
        option_df = pe_indexed if option_type == 'PE' else ce_indexed
        
        if last_ts in option_df.index:
            last_candle = option_df.loc[last_ts]
            if isinstance(last_candle, pd.DataFrame):
                last_candle = last_candle.iloc[0]
            exit_price = last_candle['close']
        else:
            exit_price = active_trade['entry_price']
        
        pnl = (exit_price - active_trade['entry_price']) * LOT_SIZE
        active_trade['exit_price'] = exit_price
        active_trade['exit_time'] = last_ts
        active_trade['result'] = 'EOD_CLOSE'
        active_trade['pnl'] = pnl
        trades.append(active_trade)
    
    return trades


# ============================================================
# MAIN
# ============================================================

def main():
    logger.info("=" * 60)
    logger.info("BACKTEST: 1-MIN DIVERGENCE STRATEGY")
    logger.info(f"SL: ₹{SL_POINTS} | TP: ₹{TP_POINTS} | Lot Size: {LOT_SIZE}")
    logger.info("=" * 60)
    
    # Load metadata
    metadata = load_metadata()
    if metadata is None:
        return
    
    logger.info(f"Data fetched at: {metadata['fetch_time']}")
    logger.info(f"CE Symbol: {metadata['ce_symbol']}")
    logger.info(f"PE Symbol: {metadata['pe_symbol']}")
    logger.info(f"ATM Strike: {metadata['atm_strike']}")
    
    trading_days = metadata['trading_days']
    all_trades = []
    
    for date_str in trading_days:
        logger.info(f"\n{'='*40}")
        logger.info(f"Processing: {date_str}")
        logger.info(f"{'='*40}")
        
        # Load 1-min data
        spot_file = f"data/nifty_spot_1min_{date_str}.csv"
        ce_file = f"data/nifty_ce_1min_{date_str}.csv"
        pe_file = f"data/nifty_pe_1min_{date_str}.csv"
        
        spot_df = load_csv_data(spot_file)
        ce_df = load_csv_data(ce_file)
        pe_df = load_csv_data(pe_file)
        
        if spot_df.empty or ce_df.empty or pe_df.empty:
            logger.warning(f"  Skipping {date_str} — missing data files")
            continue
        
        logger.info(f"  Loaded: Spot={len(spot_df)}, CE={len(ce_df)}, PE={len(pe_df)} candles")
        
        # Run backtest
        day_trades = run_backtest_for_day(date_str, spot_df, ce_df, pe_df)
        
        for t in day_trades:
            t['date'] = date_str
        
        all_trades.extend(day_trades)
        
        # Day summary
        wins = sum(1 for t in day_trades if t['result'] == 'TP')
        losses = sum(1 for t in day_trades if t['result'] == 'SL')
        eod = sum(1 for t in day_trades if t['result'] == 'EOD_CLOSE')
        day_pnl = sum(t['pnl'] for t in day_trades)
        
        logger.info(f"  Day Results: {len(day_trades)} trades | Wins: {wins} | Losses: {losses} | EOD: {eod} | PnL: ₹{day_pnl:.2f}")
    
    # ============================================================
    # FINAL SUMMARY
    # ============================================================
    logger.info(f"\n{'='*60}")
    logger.info("BACKTEST RESULTS SUMMARY")
    logger.info(f"{'='*60}")
    
    if not all_trades:
        logger.info("No trades were taken!")
        return
    
    total_trades = len(all_trades)
    winning_trades = [t for t in all_trades if t['result'] == 'TP']
    losing_trades = [t for t in all_trades if t['result'] == 'SL']
    eod_trades = [t for t in all_trades if t['result'] == 'EOD_CLOSE']
    
    total_pnl = sum(t['pnl'] for t in all_trades)
    win_pnl = sum(t['pnl'] for t in winning_trades)
    loss_pnl = sum(t['pnl'] for t in losing_trades)
    
    win_rate = (len(winning_trades) / total_trades * 100) if total_trades > 0 else 0
    
    logger.info(f"  Period: {trading_days[0]} to {trading_days[-1]}")
    logger.info(f"  Lot Size: {LOT_SIZE}")
    logger.info(f"  SL: ₹{SL_POINTS} | TP: ₹{TP_POINTS}")
    logger.info(f"")
    logger.info(f"  Total Trades:    {total_trades}")
    logger.info(f"  Winning Trades:  {len(winning_trades)}")
    logger.info(f"  Losing Trades:   {len(losing_trades)}")
    logger.info(f"  EOD Closed:      {len(eod_trades)}")
    logger.info(f"  Win Rate:        {win_rate:.1f}%")
    logger.info(f"")
    logger.info(f"  Winning PnL:     ₹{win_pnl:+.2f}")
    logger.info(f"  Losing PnL:      ₹{loss_pnl:+.2f}")
    logger.info(f"  ────────────────────────")
    logger.info(f"  Total PnL:       ₹{total_pnl:+.2f}")
    logger.info(f"{'='*60}")
    
    # Trade details table
    logger.info(f"\nDETAILED TRADE LOG:")
    logger.info(f"{'─'*120}")
    logger.info(f"{'#':>3} | {'Date':<12} | {'Type':<8} | {'Signal Time':<20} | {'Entry Time':<20} | {'Entry':>8} | {'SL':>8} | {'TP':>8} | {'Exit':>8} | {'Result':<10} | {'PnL':>10}")
    logger.info(f"{'─'*120}")
    
    for i, t in enumerate(all_trades, 1):
        signal_time = t['signal_time'].strftime('%H:%M') if hasattr(t['signal_time'], 'strftime') else str(t['signal_time'])[-8:]
        entry_time = t['entry_time'].strftime('%H:%M') if hasattr(t['entry_time'], 'strftime') else str(t['entry_time'])[-8:]
        
        logger.info(
            f"{i:>3} | {t['date']:<12} | {t['type']:<8} | {signal_time:<20} | "
            f"{entry_time:<20} | {t['entry_price']:>8.2f} | {t['sl']:>8.2f} | "
            f"{t['tp']:>8.2f} | {t['exit_price']:>8.2f} | {t['result']:<10} | ₹{t['pnl']:>+8.2f}"
        )
    
    logger.info(f"{'─'*120}")
    logger.info(f"{'':>102} TOTAL:  ₹{total_pnl:>+8.2f}")
    
    # Save results to CSV
    results_df = pd.DataFrame(all_trades)
    
    # Reorder columns
    cols = ['date', 'type', 'option', 'signal_time', 'entry_time', 'exit_time',
            'entry_price', 'sl', 'tp', 'exit_price', 'result', 'pnl', 'reason']
    results_df = results_df[[c for c in cols if c in results_df.columns]]
    
    results_file = "backtest_1min_results.csv"
    results_df.to_csv(results_file, index=False)
    logger.info(f"\nResults saved to: {results_file}")
    
    # Per-day breakdown
    logger.info(f"\nPER-DAY BREAKDOWN:")
    logger.info(f"{'─'*60}")
    for date_str in trading_days:
        day_trades = [t for t in all_trades if t['date'] == date_str]
        if day_trades:
            day_wins = sum(1 for t in day_trades if t['result'] == 'TP')
            day_losses = sum(1 for t in day_trades if t['result'] == 'SL')
            day_pnl = sum(t['pnl'] for t in day_trades)
            logger.info(f"  {date_str}: {len(day_trades)} trades | W:{day_wins} L:{day_losses} | PnL: ₹{day_pnl:+.2f}")
        else:
            logger.info(f"  {date_str}: No trades")
    logger.info(f"{'─'*60}")


if __name__ == "__main__":
    main()
